version: "3"

tasks:
  init:
    cmds:
      - echo "os init"

  # 直接编译+运行 c 代码: 已经修改编译脚本
  run:
    cmds:
      - zig build run

  test:
    cmds:
      - zig build test

  mod:init:
    cmds:
      - zigmod init

  # 手动编译方式:
  build:
    cmds:
      - zig build-exe src/main.c --library c
