version: "3"

tasks:
  init:
    cmds:
      - echo "os init"

  exec:
    cmds:
      - task: run
      - ./zig-out/bin/toolbox -h

  run:
    cmds:
      - zig build run

  test:
    cmds:
      - zig build test # zig test

  mod:init:
    cmds:
      - zigmod init

  add:
    cmds:
      - zigmod aq add 1/Hejsil/clap # clap

  fetch:
    cmds:
      - zigmod fetch
