version: "3"

################################################################################################

includes:
  basic:
    taskfile: ./packages/basic/Taskfile.yml
    dir: ./packages/basic/

  toolbox:
    taskfile: ./packages/toolbox/Taskfile.yml
    dir: ./packages/toolbox/

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  init:
    cmds:
      - echo "os init"
      - task: setup

  install:zig:
    cmds:
      - brew install zig
      - zig version
      - brew install xz # for zig zls
      - mkdir $HOME/zls && cd $HOME/zls && curl -L https://github.com/zigtools/zls/releases/download/0.9.0/x86_64-macos.tar.xz | tar -xJ --strip-components=1 -C .
      - chmod +x $HOME/zls/zls
      - sudo $HOME/zls/zls configure
    ignore_error: true

  docs:
    cmds:
      - open https://ziglang.org/zh/learn/
      - open https://ziglang.org/documentation/0.9.1/
      - open https://aquila.red/

  new:
    cmds:
      - mkdir ${NEW_PACKAGE_NAME}; cd ${NEW_PACKAGE_NAME}; zig init-exe
    dir: packages/

  new:lib:
    cmds:
      - mkdir ${NEW_PACKAGE_NAME}; cd ${NEW_PACKAGE_NAME}; zig init-lib
    dir: packages/

  run:
    cmds:
      - cd ${NEW_PACKAGE_NAME}; zig build run
    dir: packages/

  build:lib:
    cmds:
      - cd ${NEW_PACKAGE_NAME}; zig build test
    dir: packages/
