version: "3"

tasks:
  init:
    cmds:
      - echo "os init"

  # with zig v0.6.0, support `-femit-h` option
  docker:build:
    cmds:
      # - docker pull euantorano/zig:0.6.0
      - docker run --platform linux/x86_64 -v $PWD:/app euantorano/zig:0.6.0 build-lib src/mathtest.zig -femit-h
      - cp *.h src/
      - rm *.h;

  run:
    cmds:
      - zig build run

  test:
    cmds:
      - zig build test

  mod:init:
    cmds:
      - zigmod init

  # build:lib:
  #   cmds:
  #     - zig build-lib  src/mathtest.zig -femit-h -femit-h

  # build:lib:shared:
  #   cmds:
  #     - zig build-lib  src/mathtest.zig -dynamic -femit-h

  # build:exe:
  #   cmds:
  #     - zig build-exe --library libzigmath.a src/main.c

  clean:
    cmds:
      - rm -rf zig-cache/;
      - rm *.a;
      - rm *.o;
      - rm *.dylib;
    ignore_error: true
